import { Inter } from "next/font/google";
import "./globals.css";
import Aseide from "@/components/Aside/Aside";
import Asiide from "@/components/Aside/Aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
       <Asiide/>
        {children}
        
        </body>
    </html>
  );
}
